---
- name: Asible "block" module to run block of debug tasks 
  block:
    ### Block - Start ###
    - name: Block 1 - Shell, Register and Task handlers
      shell: cat /etc/hostname  | grep {{ ansible_host }}
      changed_when: false   # Even the change is "true" it will show status "OK" instead
      ignore_errors: true   # Ignore the error when it failed
      register: output_hostname
    
    - name: Block 2 - Debug variable
      debug:
        var: output_hostname

    - name: Block 3 - output only certain value
      debug:
        var: output_hostname.stdout_lines
   ### Block - End ###