---
- name: Create Ansible Service Account Group(s)
  group:
    name: "{{ item.group }}"
    state: present
  with_items: "{{ ansible_service_account }}"

- name: Create Ansible Service Account Group Home Dir(s)
  file:
    path: /home/{{ item.group }}
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ ansible_service_account }}"

- name: Create Ansible Service Account(s)
  user:
    name: "{{ item.name }}"
    home: "/home/{{ item.group }}/{{ item.name }}"
    shell: /bin/bash
    group: "{{ item.group }}"
    generate_ssh_key: true
    ssh_key_bits: 4096
  with_items: "{{ ansible_service_account }}"
  register: ansible_service_account_output

- name: Modify Ansible Service Account Home Folder Permission
  file:
    path: "/home/{{ item.group }}/{{ item.name }}"
    mode: 'g-w,o-rwx'
  with_items: "{{ ansible_service_account }}"

- name: Include Ansible Service Account(s) group sudoer Access
  lineinfile:
    path: "/etc/sudoers.d/{{ item.group }}"
    regexp: '^%{{ item.group }}'
    line: '%{{ item.group }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  with_items: "{{ ansible_service_account }}"

##### this section can be managed by Ansible Tower #####
- name: Include Authorized_keys for Ansible Service Account(s)
  authorized_key:
    user: "{{ item.name }}"
    #key: "{{ ansible_service_account_output.ssh_public_key }}"
    key: "{{ lookup('file', 'files/keys/'+ item.name + '.pub') }}"
  with_items: "{{ ansible_service_account }}"

#####
- name: debug 
  debug:
    var: ansible_service_account_output

- name: debug 
  debug:
    msg: "Please add the public key to files/keys under the role: {{ ansible_service_account_output.ssh_public_key }}"