---
- name: "Create Ansible Serive Account Group - {{ item.group }}"
  group:
    name: "{{ ansible_service_account.group }}"
    state: present
  with_items: "{{ ansible_service_account }}"

- name: "Create Ansible Serive Account Group Home Dir - {{ item.group }}"
  file:
    path: /home/{{ item.group }}
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ ansible_service_account }}"

- name: "Create Ansible Serive Account - {{ item.name }}"
  user:
    name: "{{ item.name }}"
    home: "/home/{{ item.group }}/{{ item.name }}"
    shell: /bin/bash
    group: "{{ item.group }}"
  with_items: "{{ ansible_service_account }}"

- name: Change Ansible Service Account Home Folder Permission
  file:
    path: "/home/{{ item.group }}/{{ item.name }}"
    mode: 'g-w,o-rwx'
  with_items: "{{ ansible_service_account }}"

#- name: "Add RSA keys"
#  authorized_key:
#    user: "{{ item.name }}"
#    key: "{{ lookup('file', 'files/keys/'+ item.name + '.pub') }}"
#  with_items: "{{ ansible_service_account }}"

- name: Add user(s) to sudoer
  lineinfile:
    path: "/etc/sudoers.d/{{ item.group }}"
    line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  with_items: "{{ ansible_service_account }}"