---
# tasks file for common
# https://www.redhat.com/sysadmin/ansible-tags-fast-playbook-runs
- include_tasks: 
    file: copy.yml
    apply:
      tags:
        - tag-copy
  tags:
    - always
- import_tasks: template.yml
  tags:
    - tag-template
- include_tasks: ansible_facts.yml
- include_tasks: block_register_degug.yml
- include_tasks: withitems.yml
- include_tasks: set_fact.yml