---
# tasks file for common
# https://www.redhat.com/sysadmin/ansible-tags-fast-playbook-runs

- import_tasks: copy.yml
  tags:
    - module-copy

- import_tasks: template.yml
  tags:
    - module-template

- import_tasks: ansible_facts.yml
  tags:
    - module-ansible_facts

- import_tasks: block_register_degug.yml
  tags:
    - module-block
    - module-register
    - module-debug

- import_tasks: withitems.yml
  tags:
    - module-with_items

- import_tasks: set_fact.yml
  tags:
    - module-set_fact