---
# tasks file for common
- include_tasks: 
    file: copy.yml
    apply:
      tags:
        - tag-copy
  tags:
    - always
- include_tasks: template.yml
- include_tasks: ansible_facts.yml
- include_tasks: block_register_degug.yml
- include_tasks: withitems.yml
- include_tasks: set_fact.yml