---
- name: Ansible "template" module
  template:
    src: hostinfo.j2
    dest: "{{ ansible_env.HOME }}/ansible-results/hostinfo.txt"
  register: output_template

- name: print the template output
  shell: "cat {{ output_template.path }}"
  register: output_template2
  changed_when: false

- debug:
    msg: "{{ output_template2.stdout }}"