---
- name: Ansible "template" module
  template:
    src: hostinfo.j2
    dest: "{{ ansible_env.HOME }}/ansible-results/hostinfo.txt"
  register: output_template_module

- name: capture template the template output
  shell: "cat {{ output_template_module.path }}"
  register: output_template_info
  changed_when: false

- name: echo template contents
  debug:
    msg: "{{ output_template_info.stdout }}"